# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ip_address',
            field=models.CharField(default='abc', max_length=120),
        ),
    ]
