# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0002_join_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
