# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0003_auto_20170121_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='abc', max_length=120),
        ),
    ]
