# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0006_auto_20170121_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='abc', max_length=120),
        ),
    ]
