# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0007_auto_20170121_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='join',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='abc', max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='joinfriends',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Sharer', to='joins.Join'),
        ),
        migrations.AddField(
            model_name='joinfriends',
            name='emailall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailall', to='joins.Join'),
        ),
        migrations.AddField(
            model_name='joinfriends',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='Friend', to='joins.Join'),
        ),
    ]
